declare module '@ant-design/icons' {
  import * as React from 'react';

  // Base Icon interface
  export interface IconProps {
    className?: string;
    style?: React.CSSProperties;
    spin?: boolean;
    rotate?: number;
    twoToneColor?: string;
    [key: string]: any;
  }

  // Icon Component
  export const Icon: React.FC<IconProps & {
    component: React.ComponentType<any>;
  }>;

  // Commonly used icons
  export const DownOutlined: React.FC<IconProps>;
  export const UpOutlined: React.FC<IconProps>;
  export const LeftOutlined: React.FC<IconProps>;
  export const RightOutlined: React.FC<IconProps>;
  export const QuestionCircleOutlined: React.FC<IconProps>;
  export const InfoCircleOutlined: React.FC<IconProps>;
  export const CheckCircleOutlined: React.FC<IconProps>;
  export const CloseCircleOutlined: React.FC<IconProps>;
  export const ExclamationCircleOutlined: React.FC<IconProps>;
  export const LoadingOutlined: React.FC<IconProps>;
  export const SearchOutlined: React.FC<IconProps>;
  export const SettingOutlined: React.FC<IconProps>;
  export const FileOutlined: React.FC<IconProps>;
  export const FolderOutlined: React.FC<IconProps>;
  export const UserOutlined: React.FC<IconProps>;
  export const TeamOutlined: React.FC<IconProps>;
  export const HomeOutlined: React.FC<IconProps>;
  export const CalendarOutlined: React.FC<IconProps>;
  export const BellOutlined: React.FC<IconProps>;
  export const MenuOutlined: React.FC<IconProps>;
  export const AppstoreOutlined: React.FC<IconProps>;
  export const BarChartOutlined: React.FC<IconProps>;
  export const PieChartOutlined: React.FC<IconProps>;
  export const LineChartOutlined: React.FC<IconProps>;
  export const DotChartOutlined: React.FC<IconProps>;
  export const RadarChartOutlined: React.FC<IconProps>;
  export const HeatMapOutlined: React.FC<IconProps>;
  export const ArrowUpOutlined: React.FC<IconProps>;
  export const ArrowDownOutlined: React.FC<IconProps>;
  export const ArrowLeftOutlined: React.FC<IconProps>;
  export const ArrowRightOutlined: React.FC<IconProps>;
  export const PlusOutlined: React.FC<IconProps>;
  export const MinusOutlined: React.FC<IconProps>;
  export const CloseOutlined: React.FC<IconProps>;
  export const CheckOutlined: React.FC<IconProps>;
  export const EllipsisOutlined: React.FC<IconProps>;
  export const DeleteOutlined: React.FC<IconProps>;
  export const EditOutlined: React.FC<IconProps>;
  export const CopyOutlined: React.FC<IconProps>;
  export const SaveOutlined: React.FC<IconProps>;
  export const SendOutlined: React.FC<IconProps>;
  export const UploadOutlined: React.FC<IconProps>;
  export const DownloadOutlined: React.FC<IconProps>;
  export const ReloadOutlined: React.FC<IconProps>;
  export const SyncOutlined: React.FC<IconProps>;
  export const PlayCircleOutlined: React.FC<IconProps>;
  export const PauseCircleOutlined: React.FC<IconProps>;
  export const StopOutlined: React.FC<IconProps>;
  export const CaretUpOutlined: React.FC<IconProps>;
  export const CaretDownOutlined: React.FC<IconProps>;
  export const CaretLeftOutlined: React.FC<IconProps>;
  export const CaretRightOutlined: React.FC<IconProps>;
  export const FastBackwardOutlined: React.FC<IconProps>;
  export const FastForwardOutlined: React.FC<IconProps>;
  export const StepBackwardOutlined: React.FC<IconProps>;
  export const StepForwardOutlined: React.FC<IconProps>;
  export const EyeOutlined: React.FC<IconProps>;
  export const EyeInvisibleOutlined: React.FC<IconProps>;
  export const LockOutlined: React.FC<IconProps>;
  export const UnlockOutlined: React.FC<IconProps>;
  export const KeyOutlined: React.FC<IconProps>;
  export const MailOutlined: React.FC<IconProps>;
  export const PhoneOutlined: React.FC<IconProps>;
  export const MobileOutlined: React.FC<IconProps>;
  export const TabletOutlined: React.FC<IconProps>;
  export const LaptopOutlined: React.FC<IconProps>;
  export const DesktopOutlined: React.FC<IconProps>;
  export const CloudOutlined: React.FC<IconProps>;
  export const CloudDownloadOutlined: React.FC<IconProps>;
  export const CloudUploadOutlined: React.FC<IconProps>;
  export const CloudServerOutlined: React.FC<IconProps>;
  export const GlobalOutlined: React.FC<IconProps>;
  export const ShopOutlined: React.FC<IconProps>;
  export const ShoppingCartOutlined: React.FC<IconProps>;
  export const ShoppingOutlined: React.FC<IconProps>;
  export const PayCircleOutlined: React.FC<IconProps>;
  export const DollarOutlined: React.FC<IconProps>;
  export const EuroOutlined: React.FC<IconProps>;
  export const PoundOutlined: React.FC<IconProps>;
  export const WalletOutlined: React.FC<IconProps>;
  export const StarOutlined: React.FC<IconProps>;
  export const StarFilled: React.FC<IconProps>;
  export const HeartOutlined: React.FC<IconProps>;
  export const HeartFilled: React.FC<IconProps>;
  export const CheckCircleFilled: React.FC<IconProps>;
  export const CloseCircleFilled: React.FC<IconProps>;
  export const InfoCircleFilled: React.FC<IconProps>;
  export const ExclamationCircleFilled: React.FC<IconProps>;
  export const QuestionCircleFilled: React.FC<IconProps>;
  export const WarningFilled: React.FC<IconProps>;
  export const FileTextOutlined: React.FC<IconProps>;
  export const FileImageOutlined: React.FC<IconProps>;
  export const FilePdfOutlined: React.FC<IconProps>;
  export const FileExcelOutlined: React.FC<IconProps>;
  export const FileWordOutlined: React.FC<IconProps>;
  export const FilePptOutlined: React.FC<IconProps>;
  export const FileMarkdownOutlined: React.FC<IconProps>;
  export const FileZipOutlined: React.FC<IconProps>;
  export const FileUnknownOutlined: React.FC<IconProps>;
  export const CommentOutlined: React.FC<IconProps>;
  export const MessageOutlined: React.FC<IconProps>;
  export const LikeOutlined: React.FC<IconProps>;
  export const DislikeOutlined: React.FC<IconProps>;
  export const RobotOutlined: React.FC<IconProps>;
  export const BugOutlined: React.FC<IconProps>;
  export const CodeOutlined: React.FC<IconProps>;
  export const CodeSandboxOutlined: React.FC<IconProps>;
  export const GithubOutlined: React.FC<IconProps>;
  export const GitlabOutlined: React.FC<IconProps>;
  export const AppleOutlined: React.FC<IconProps>;
  export const AndroidOutlined: React.FC<IconProps>;
  export const WindowsOutlined: React.FC<IconProps>;
  export const ChromeOutlined: React.FC<IconProps>;
  export const IeOutlined: React.FC<IconProps>;
  export const FacebookOutlined: React.FC<IconProps>;
  export const TwitterOutlined: React.FC<IconProps>;
  export const InstagramOutlined: React.FC<IconProps>;
  export const LinkedinOutlined: React.FC<IconProps>;
  export const YoutubeOutlined: React.FC<IconProps>;
  export const SlackOutlined: React.FC<IconProps>;
  export const SkypeOutlined: React.FC<IconProps>;
  export const WechatOutlined: React.FC<IconProps>;
  export const AlipayOutlined: React.FC<IconProps>;
  export const TaobaoOutlined: React.FC<IconProps>;
  export const ZhihuOutlined: React.FC<IconProps>;
  export const DashboardOutlined: React.FC<IconProps>;
  export const ControlOutlined: React.FC<IconProps>;
  export const FormOutlined: React.FC<IconProps>;
  export const TableOutlined: React.FC<IconProps>;
  export const ProfileOutlined: React.FC<IconProps>;
  export const ProjectOutlined: React.FC<IconProps>;
  export const SolutionOutlined: React.FC<IconProps>;
  export const ToolOutlined: React.FC<IconProps>;
  export const FundOutlined: React.FC<IconProps>;
  export const MonitorOutlined: React.FC<IconProps>;
  export const ClusterOutlined: React.FC<IconProps>;
  export const ApiOutlined: React.FC<IconProps>;
  export const ApartmentOutlined: React.FC<IconProps>;
  export const FundProjectionScreenOutlined: React.FC<IconProps>;
  export const ExperimentOutlined: React.FC<IconProps>;
  export const RocketOutlined: React.FC<IconProps>;
  export const ThunderboltOutlined: React.FC<IconProps>;
  export const PoweroffOutlined: React.FC<IconProps>;
  export const FireOutlined: React.FC<IconProps>;

  // Two tone icons
  export const CheckCircleTwoTone: React.FC<IconProps>;
  export const ExclamationCircleTwoTone: React.FC<IconProps>;
  export const InfoCircleTwoTone: React.FC<IconProps>;
  export const CloseCircleTwoTone: React.FC<IconProps>;
  export const HeartTwoTone: React.FC<IconProps>;
  export const StarTwoTone: React.FC<IconProps>;

  // Filled icons
  export const CheckCircleFilled: React.FC<IconProps>;
  export const CloseCircleFilled: React.FC<IconProps>;
  export const ExclamationCircleFilled: React.FC<IconProps>;
  export const InfoCircleFilled: React.FC<IconProps>;
  export const StarFilled: React.FC<IconProps>;
  export const HeartFilled: React.FC<IconProps>;
} 